# Generated by Django 4.1.1 on 2022-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('Todos', 'Todos'), ('Accesorios', 'Accesorios'), ('Farmacia', 'Farmacia'), ('Cuidado de la Piel', 'Cuidado de la Piel'), ('Cuidado de la Salud', 'Cuidado de la Salud'), ('Cuidado Personal', 'Cuidado Personal'), ('Bebes y Niños', 'Bebes y Niños'), ('Salud Sexual', 'Salud Sexual')], max_length=25)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
