# Generated by Django 4.1.1 on 2023-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=5)),
                ('usuario', models.CharField(max_length=100)),
                ('totalCarrito', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Ordenes',
                'db_table': 'tienda_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(null=True)),
                ('codProducto', models.CharField(max_length=4, null=True)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acumulado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'tienda_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('Todos', 'Todos'), ('Accesorios', 'Accesorios'), ('Farmacia', 'Farmacia'), ('Cuidado de la Piel', 'Cuidado de la Piel'), ('Cuidado de la Salud', 'Cuidado de la Salud'), ('Cuidado Personal', 'Cuidado Personal'), ('Bebes y Niños', 'Bebes y Niños'), ('Salud Sexual', 'Salud Sexual')], max_length=25)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('codProducto', models.CharField(max_length=4, null=True)),
                ('nombreProducto', models.CharField(max_length=60, null=True)),
                ('imagen', models.ImageField(blank=True, default='default_prod.png', upload_to='img-productos')),
            ],
            options={
                'db_table': 'tienda_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosDestacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acumulador', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tienda_productosdestacados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaArticulos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigogenerico', models.CharField(db_column='codigoGenerico', max_length=20)),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('fechmod', models.DateTimeField(db_column='FechMod')),
            ],
            options={
                'db_table': 'tienda_articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaProductos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codProducto', models.CharField(blank=True, db_column='codProducto', max_length=4, null=True)),
                ('producto', models.CharField(blank=True, max_length=25, null=True)),
                ('codigoGenerico', models.CharField(db_column='codigoGenerico', max_length=20)),
                ('descProducto', models.CharField(db_column='descProducto', max_length=50)),
                ('stockProducto', models.FloatField(db_column='stockProducto')),
                ('precio', models.FloatField()),
                ('fechMod', models.DateTimeField(db_column='fechMod')),
                ('imagen', models.ImageField(default='default_prod.png', upload_to='img-productos')),
                ('categoria', models.CharField(choices=[('Accesorios', 'Accesorios'), ('Farmacia', 'Farmacia')], max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'tienda_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaStock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigogenerico', models.CharField(db_column='codigoGenerico', max_length=20)),
                ('cantum1', models.FloatField(db_column='cantUM1')),
                ('cantum2', models.FloatField(db_column='cantUM2')),
            ],
            options={
                'db_table': 'tienda_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaStockproducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codproducto', models.CharField(blank=True, db_column='codProducto', max_length=4, null=True)),
                ('producto', models.CharField(blank=True, max_length=25, null=True)),
                ('codigogenerico', models.CharField(db_column='codigoGenerico', max_length=20)),
                ('descproducto', models.CharField(db_column='descProducto', max_length=50)),
                ('stockproducto', models.FloatField(db_column='stockProducto')),
                ('stockdescproducto', models.FloatField(db_column='stockDescProducto')),
            ],
            options={
                'db_table': 'tienda_stockProducto',
                'managed': False,
            },
        ),
    ]
