# Generated by Django 4.1.1 on 2023-02-03 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=5)),
                ('usuario', models.CharField(max_length=100)),
                ('totalCarrito', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('Todos', 'Todos'), ('Accesorios', 'Accesorios'), ('Farmacia', 'Farmacia'), ('Cuidado de la Piel', 'Cuidado de la Piel'), ('Cuidado de la Salud', 'Cuidado de la Salud'), ('Cuidado Personal', 'Cuidado Personal'), ('Bebes y Niños', 'Bebes y Niños'), ('Salud Sexual', 'Salud Sexual')], max_length=25)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('codProducto', models.CharField(max_length=4, null=True)),
                ('nombreProducto', models.CharField(max_length=60, null=True)),
                ('imagen', models.ImageField(blank=True, default='default_prod.png', upload_to='img-productos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(null=True)),
                ('codProducto', models.CharField(max_length=4, null=True)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acumulado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('nroPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.orden')),
            ],
        ),
    ]
