# Generated by Django 4.1.1 on 2023-02-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCancelado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(null=True)),
                ('codProducto', models.CharField(max_length=4, null=True)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acumulado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.IntegerField()),
                ('nroPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.orden')),
            ],
        ),
    ]
