# Generated by Django 4.1.1 on 2023-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pedidocancelado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocancelado',
            options={'managed': False},
        ),
    ]
