# Generated by Django 4.1.1 on 2023-01-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_pedido_nropedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Ordenes'},
        ),
    ]
