# Generated by Django 4.1.1 on 2022-11-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
