# Generated by Django 4.1.1 on 2022-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(choices=[('-----', '-----'), ('Administracion', 'Administracion'), ('Sistemas', 'Sistemas'), ('Imagen', 'Imagen'), ('RRHH', 'RRHH'), ('Abastecimiento', 'Abastecimiento'), ('Mantenimiento', 'Mantenimiento'), ('Gerentes', 'Gerentes'), ('Compras', 'Compras'), ('Legales', 'Legales'), ('Otra', 'Otra')], max_length=25, verbose_name='Area'),
        ),
    ]
