# Generated by Django 4.1.1 on 2022-11-24 12:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0015_alter_area_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('area', models.CharField(choices=[('None', 'None'), ('Administracion', 'Administracion'), ('Sistemas', 'Sistemas'), ('Imagen', 'Imagen'), ('RRHH', 'RRHH'), ('Abastecimiento', 'Abastecimiento'), ('Mantenimiento', 'Mantenimiento'), ('Gerentes', 'Gerentes'), ('Compras', 'Compras'), ('Legales', 'Legales'), ('Otra', 'Otra')], max_length=25, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
