# Generated by Django 4.1.1 on 2022-12-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_legajo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajo',
            name='legajo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Legajo'),
        ),
    ]
