# Generated by Django 4.1.1 on 2022-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_legajo_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajo',
            name='legajo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Legajo'),
        ),
    ]
