# Generated by Django 4.1.1 on 2022-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_legajo_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajo',
            name='legajo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Legajo'),
        ),
    ]
