# Generated by Django 4.1.1 on 2023-01-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_alter_legajo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Administracion', 'Administracion'), ('Sistemas', 'Sistemas'), ('Imagen', 'Imagen'), ('RRHH', 'RRHH'), ('Abastecimiento', 'Abastecimiento'), ('Mantenimiento', 'Mantenimiento'), ('Gerentes', 'Gerentes'), ('Compras', 'Compras'), ('Legales', 'Legales'), ('Otra', 'Otra')], max_length=25, null=True, verbose_name='Area'),
        ),
    ]
